#!/usr/bin/env python
# coding: utf-8
"""Local-first subtitle generation shared by the Modern and SmallTool GUIs.

Japanese speech recognition runs via the official whisper.cpp Windows build.
English and Taiwan Traditional Chinese translation defaults to pinned,
integrity-checked local models.  A user can instead opt in to a configured LLM
provider, in which case only Japanese subtitle cue text is sent to that
provider; video and audio always remain on the computer.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import secrets
import shutil
import sqlite3
import subprocess
import sys
import tempfile
import threading
import time
import unicodedata
import zipfile
from contextlib import contextmanager
from dataclasses import dataclass
from functools import lru_cache
from typing import Callable, Iterable, Optional
from urllib.parse import quote, urlsplit, urlunsplit

import requests

import config
from M3U8Sites.M3U8Crawler import locate_ffmpeg
from ssl_util import SharedSSLAdapter


WHISPER_VERSION = 'v1.9.1'
WHISPER_ARCHIVE_URL = (
    'https://github.com/ggml-org/whisper.cpp/releases/download/'
    f'{WHISPER_VERSION}/whisper-bin-x64.zip'
)
WHISPER_ARCHIVE_SHA256 = (
    '7d8be46ecd31828e1eb7a2ecdd0d6b314feafd82163038ab6092594b0a063539'
)
WHISPER_ARCHIVE_SIZE = 7_982_101
WHISPER_RUNTIME_FILES = {
    'Release/whisper-cli.exe': (
        479_232,
        '58245314fb73b30fbd0cf0542c5c172e23f02b6eb7cad7b51e792439cf5e1755',
    ),
    'Release/whisper.dll': (
        1_366_016,
        'b31690c12461517fe9774e61318ab63a69972b948151feed98b913be35f708b6',
    ),
    'Release/ggml-base.dll': (
        656_384,
        '8be6f3e06388b3a9aac75d29bec86363e2e2f5b0cee86ce6438866bcac0bcf86',
    ),
    'Release/ggml.dll': (
        67_584,
        'db753141098018ab482796052a61e727ee0106cbc280f28397f6a111b5e667d7',
    ),
    'Release/ggml-cpu-alderlake.dll': (
        790_528,
        '323408503da53ccc67248b26d711f16d73d2d6239f7703a00a6a18b60ed5b8b8',
    ),
    'Release/ggml-cpu-cannonlake.dll': (
        833_536,
        '0f659d98b823bb871c7845787bba7485facd220099cf58aa773652b9b842ab2e',
    ),
    'Release/ggml-cpu-cascadelake.dll': (
        830_976,
        '8116b0e516134139de29400c536ecf06fe708ce1a078a96d30b562b30d524fbe',
    ),
    'Release/ggml-cpu-haswell.dll': (
        791_552,
        'e5925923a47672392f9e9c8c92e4b9b65ea473948bf4f568a0300a3a42485135',
    ),
    'Release/ggml-cpu-icelake.dll': (
        830_976,
        'b726d528bee0c811c6b2ad8775357379d651cabb487bbf800331697fe73da187',
    ),
    'Release/ggml-cpu-sandybridge.dll': (
        783_360,
        '1c49c64817233b2447ca305b41c66afa4bed31b058bc190a98af2a30cc703542',
    ),
    'Release/ggml-cpu-skylakex.dll': (
        833_536,
        '06082dc62a09a82fbba4aab49b2c049b96db84c5fc561a446a8ddbfb9b20bf86',
    ),
    'Release/ggml-cpu-sse42.dll': (
        772_096,
        '9a8f55ff1dfad231aa6250ac52c330c5bfa5c4c37691c8b591a68b52090ce40c',
    ),
    'Release/ggml-cpu-x64.dll': (
        776_704,
        '45ff644d301b8a1fffc7c5e3864205047360eb197814c7311f366d106bb5b19f',
    ),
}

MODEL_NAME = 'ggml-base-q5_1.bin'
MODEL_URL = f'https://huggingface.co/ggerganov/whisper.cpp/resolve/main/{MODEL_NAME}'
MODEL_SHA256 = '422f1ae452ade6f30a004d7e5c6a43195e4433bc370bf23fac9cc591f01a8898'
MODEL_SIZE = 59_707_625

VAD_MODEL_NAME = 'ggml-silero-v6.2.0.bin'
VAD_MODEL_URL = (
    'https://huggingface.co/ggml-org/whisper-vad/resolve/main/'
    + VAD_MODEL_NAME
)
VAD_MODEL_SHA256 = '2aa269b785eeb53a82983a20501ddf7c1d9c48e33ab63a41391ac6c9f7fb6987'
VAD_MODEL_SIZE = 885_098

TRANSLATION_PACK_VERSION = '1'
TRANSLATION_PACK_NAME = f'Jable_local_translation_v{TRANSLATION_PACK_VERSION}.zip'
TRANSLATION_PACK_RELEASE_TAG = 'v2.5.34'
TRANSLATION_PACK_URL = (
    'https://github.com/Alos21750/JableTV-MissAV-Downloader-GUI-2026/'
    f'releases/download/{TRANSLATION_PACK_RELEASE_TAG}/'
    f'{TRANSLATION_PACK_NAME}'
)
# Generated by scripts/build_local_translation_pack.py from the pinned
# CC BY-SA 4.0 FuguMT ja-en and Apache-2.0 OPUS-MT en-zh revisions documented
# in the pack manifest. These values change only with a reproducible rebuild.
TRANSLATION_PACK_SHA256 = (
    '1259a2abeb5026411da39c6f3dcd69ebd70bed654ac9cfaaee0c7373867c0bb4'
)
TRANSLATION_PACK_SIZE = 147_330_565
TRANSLATION_MANIFEST_SHA256 = (
    '1ac2f8c0a0bae7f934b3d8eb765e8f2b199a02bcecf6ab7f31396915a5f1a135'
)
TRANSLATION_ENGINE_VERSION = (
    f'fugumt-opus-ct2-int8-v{TRANSLATION_PACK_VERSION}')
VALID_SUBTITLE_MODES = {'none', 'ja', 'en', 'zh', 'all'}

ProgressCallback = Callable[[str, Optional[int]], None]
CancelCheck = Callable[[], bool]

_runtime_lock = threading.Lock()
_generation_lock = threading.Lock()
_translation_runtime_lock = threading.Lock()
_translation_memory_lock = threading.Lock()
_translation_provider_state = threading.local()
_verified_paths: dict[str, tuple[int, int, int, int, int, str]] = {}


class SubtitleError(RuntimeError):
    """A user-facing subtitle generation failure."""


class SubtitleCancelled(SubtitleError):
    """Raised when the owning download job is cancelled."""


@dataclass(frozen=True)
class SubtitleResult:
    files: tuple[str, ...]
    generated: tuple[str, ...]


@dataclass(frozen=True)
class SrtCue:
    index: str
    timing: str
    text: str


def normalize_subtitle_mode(value) -> str:
    mode = str(value or '').strip().lower()
    aliases = {
        'off': 'none', 'disabled': 'none',
        'jp': 'ja', 'japanese': 'ja',
        'english': 'en',
        'zh-tw': 'zh', 'traditional-chinese': 'zh', 'chinese': 'zh',
        'multi': 'all', 'multilingual': 'all',
    }
    mode = aliases.get(mode, mode)
    return mode if mode in VALID_SUBTITLE_MODES else 'none'


def subtitle_languages(mode) -> tuple[str, ...]:
    mode = normalize_subtitle_mode(mode)
    if mode == 'all':
        return ('ja', 'en', 'zh-TW')
    if mode == 'zh':
        return ('zh-TW',)
    if mode in ('ja', 'en'):
        return (mode,)
    return ()


def subtitle_paths(video_path: str) -> dict[str, str]:
    stem = os.path.splitext(os.path.abspath(video_path))[0]
    return {
        'ja': stem + '.ja.srt',
        'en': stem + '.en.srt',
        'zh-TW': stem + '.zh-TW.srt',
    }


def parse_srt(text: str) -> list[SrtCue]:
    normalized = str(text or '').lstrip('\ufeff').replace('\r\n', '\n').replace('\r', '\n')
    blocks = re.split(r'\n[ \t]*\n', normalized.strip()) if normalized.strip() else []
    cues: list[SrtCue] = []
    for block in blocks:
        lines = block.split('\n')
        if len(lines) < 3 or '-->' not in lines[1]:
            raise SubtitleError('Whisper produced an invalid SRT subtitle file')
        cue_text = '\n'.join(lines[2:]).strip()
        cues.append(SrtCue(lines[0].strip(), lines[1].strip(), cue_text))
    return cues


def render_srt(cues: Iterable[SrtCue]) -> str:
    parts = []
    for cue in cues:
        parts.append(f'{cue.index}\n{cue.timing}\n{cue.text.strip()}')
    return '\n\n'.join(parts) + ('\n' if parts else '')


def _cache_root() -> str:
    base = (os.environ.get('LOCALAPPDATA') or os.environ.get('APPDATA')
            or os.path.join(os.path.expanduser('~'), '.cache'))
    return os.path.join(base, 'JableTV Downloader', 'subtitle_tools')


@contextmanager
def _interprocess_cache_lock(
        name: str, cancel_check: Optional[CancelCheck],
        timeout_seconds: float = 15 * 60):
    """Serialize shared-cache installation across both frozen applications."""
    lock_dir = os.path.join(_cache_root(), '.locks')
    os.makedirs(lock_dir, exist_ok=True)
    safe_name = re.sub(r'[^A-Za-z0-9_.-]+', '-', str(name or 'cache'))
    path = os.path.join(lock_dir, safe_name + '.lock')
    handle = open(path, 'a+b')
    acquired = False
    deadline = time.monotonic() + max(1.0, float(timeout_seconds))
    try:
        handle.seek(0, os.SEEK_END)
        if handle.tell() == 0:
            handle.write(b'\0')
            handle.flush()

        while not acquired:
            _check_cancel(cancel_check)
            try:
                handle.seek(0)
                if os.name == 'nt':
                    import msvcrt
                    msvcrt.locking(handle.fileno(), msvcrt.LK_NBLCK, 1)
                else:
                    import fcntl
                    fcntl.flock(handle.fileno(), fcntl.LOCK_EX | fcntl.LOCK_NB)
                acquired = True
            except (OSError, BlockingIOError):
                if time.monotonic() >= deadline:
                    raise SubtitleError(
                        'Timed out waiting for another subtitle model install')
                time.sleep(0.1)
        yield
    finally:
        if acquired:
            try:
                handle.seek(0)
                if os.name == 'nt':
                    import msvcrt
                    msvcrt.locking(handle.fileno(), msvcrt.LK_UNLCK, 1)
                else:
                    import fcntl
                    fcntl.flock(handle.fileno(), fcntl.LOCK_UN)
            except OSError:
                pass
        handle.close()


def _notify(callback: Optional[ProgressCallback], stage: str,
            percent: Optional[int] = None) -> None:
    if callback:
        callback(stage, percent)


def _check_cancel(cancel_check: Optional[CancelCheck]) -> None:
    if cancel_check and cancel_check():
        raise SubtitleCancelled('Subtitle generation cancelled')


def _session() -> requests.Session:
    session = requests.Session()
    session.mount('https://', SharedSSLAdapter(pool_connections=4, pool_maxsize=4))
    session.headers.update({
        'User-Agent': config.headers.get('User-Agent', 'JableTV Downloader'),
        'Accept-Language': 'zh-TW,zh;q=0.9,en;q=0.8,ja;q=0.7',
    })
    return session


def _sha256(
        path: str,
        cancel_check: Optional[CancelCheck] = None) -> str:
    digest = hashlib.sha256()
    with open(path, 'rb') as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b''):
            _check_cancel(cancel_check)
            digest.update(chunk)
    return digest.hexdigest()


def _is_verified(
        path: str, expected_size: int, expected_sha256: str,
        cancel_check: Optional[CancelCheck] = None) -> bool:
    key = os.path.abspath(path)
    try:
        before = os.stat(path)
        if not os.path.isfile(path) or before.st_size != expected_size:
            _verified_paths.pop(key, None)
            return False
        expected_hash = expected_sha256.lower()
        identity = (
            int(before.st_size),
            int(before.st_mtime_ns),
            int(before.st_ctime_ns),
            int(getattr(before, 'st_ino', 0)),
            int(expected_size),
            expected_hash,
        )
        if _verified_paths.get(key) == identity:
            return True
        if _sha256(path, cancel_check).lower() != expected_hash:
            _verified_paths.pop(key, None)
            return False
        after = os.stat(path)
        after_identity = (
            int(after.st_size),
            int(after.st_mtime_ns),
            int(after.st_ctime_ns),
            int(getattr(after, 'st_ino', 0)),
            int(expected_size),
            expected_hash,
        )
        if after_identity != identity:
            _verified_paths.pop(key, None)
            return False
    except OSError:
        _verified_paths.pop(key, None)
        return False
    _verified_paths[key] = identity
    return True


def _download_verified(url: str, destination: str, expected_size: int,
                       expected_sha256: str, stage: str,
                       progress_callback: Optional[ProgressCallback],
                       cancel_check: Optional[CancelCheck]) -> str:
    if _is_verified(
            destination, expected_size, expected_sha256, cancel_check):
        return destination

    os.makedirs(os.path.dirname(destination), exist_ok=True)
    part = destination + '.part'
    try:
        os.remove(part)
    except FileNotFoundError:
        pass

    session = _session()
    try:
        kwargs = config.proxy_request_kwargs()
        # A short per-read timeout keeps cancellation responsive when a model
        # host stalls; the timeout resets whenever another chunk arrives.
        with session.get(url, stream=True, timeout=(15, 15), **kwargs) as response:
            response.raise_for_status()
            received = 0
            total = int(response.headers.get('Content-Length') or expected_size)
            with open(part, 'wb') as handle:
                for chunk in response.iter_content(chunk_size=1024 * 1024):
                    _check_cancel(cancel_check)
                    if not chunk:
                        continue
                    if received + len(chunk) > expected_size:
                        raise SubtitleError(
                            'Downloaded subtitle component is larger than expected')
                    handle.write(chunk)
                    received += len(chunk)
                    pct = int(received * 100 / total) if total > 0 else None
                    _notify(progress_callback, stage, min(100, pct) if pct is not None else None)
                handle.flush()
                os.fsync(handle.fileno())
        if not _is_verified(
                part, expected_size, expected_sha256, cancel_check):
            raise SubtitleError('Downloaded subtitle component failed integrity verification')
        os.replace(part, destination)
        _verified_paths.pop(os.path.abspath(part), None)
        _verified_paths.pop(os.path.abspath(destination), None)
        if not _is_verified(
                destination, expected_size, expected_sha256, cancel_check):
            raise SubtitleError('Installed subtitle component failed integrity verification')
        return destination
    except SubtitleCancelled:
        raise
    except SubtitleError:
        raise
    except Exception as exc:
        raise SubtitleError(f'Unable to download subtitle component: {type(exc).__name__}') from exc
    finally:
        session.close()
        try:
            os.remove(part)
        except FileNotFoundError:
            pass


def _find_whisper_exe(folder: str) -> Optional[str]:
    if not os.path.isdir(folder):
        return None
    for root, _dirs, files in os.walk(folder):
        for filename in files:
            if filename.lower() == 'whisper-cli.exe':
                return os.path.join(root, filename)
    return None


def _verify_whisper_install(
        folder: str, require_marker: bool = True,
        cancel_check: Optional[CancelCheck] = None) -> Optional[str]:
    _check_cancel(cancel_check)
    if not os.path.isdir(folder):
        return None
    if require_marker:
        try:
            with open(
                    os.path.join(folder, '.source-sha256'),
                    'r', encoding='ascii') as handle:
                if (
                        handle.read().strip().lower()
                        != WHISPER_ARCHIVE_SHA256.lower()):
                    return None
        except OSError:
            return None
    for relative_path, (expected_size, expected_sha256) in (
            WHISPER_RUNTIME_FILES.items()):
        _check_cancel(cancel_check)
        path = os.path.join(folder, *relative_path.split('/'))
        if not _is_verified(
                path, expected_size, expected_sha256, cancel_check):
            return None
    return os.path.join(folder, 'Release', 'whisper-cli.exe')


def _safe_extract_zip(
        archive: str, destination: str,
        progress_callback: Optional[ProgressCallback] = None,
        cancel_check: Optional[CancelCheck] = None,
        progress_stage: Optional[str] = None,
        progress_start: int = 0,
        progress_end: int = 100) -> None:
    root = os.path.abspath(destination)
    try:
        with zipfile.ZipFile(archive) as bundle:
            infos = bundle.infolist()
            if len(infos) > 4096:
                raise SubtitleError(
                    'Subtitle component archive contains too many files')
            total_size = sum(info.file_size for info in infos)
            if total_size > 300 * 1024 * 1024:
                raise SubtitleError(
                    'Subtitle component archive is unexpectedly large')

            seen: set[str] = set()
            extracted = 0
            if progress_stage:
                _notify(progress_callback, progress_stage, progress_start)
            for info in infos:
                _check_cancel(cancel_check)
                member = info.filename.replace('\\', '/')
                is_directory = info.is_dir() or member.endswith('/')
                member = member.rstrip('/')
                parts = member.split('/')
                normalized_member = os.path.normcase(member).casefold()
                if (
                        not member
                        or member.startswith('/')
                        or ':' in member
                        or any(part in ('', '.', '..') for part in parts)
                        or normalized_member in seen):
                    raise SubtitleError(
                        'Unsafe path found in subtitle component archive')
                seen.add(normalized_member)
                file_type = (info.external_attr >> 16) & 0o170000
                if file_type == 0o120000:
                    raise SubtitleError(
                        'Unsafe link found in subtitle component archive')
                if is_directory:
                    continue
                target = os.path.abspath(os.path.join(root, *parts))
                if os.path.commonpath([root, target]) != root:
                    raise SubtitleError(
                        'Unsafe path found in subtitle component archive')
                os.makedirs(os.path.dirname(target), exist_ok=True)
                with bundle.open(info) as source, open(target, 'wb') as output:
                    while True:
                        _check_cancel(cancel_check)
                        chunk = source.read(1024 * 1024)
                        if not chunk:
                            break
                        output.write(chunk)
                        extracted += len(chunk)
                        if progress_stage and total_size:
                            percent = progress_start + int(
                                extracted * (progress_end - progress_start)
                                / total_size)
                            _notify(
                                progress_callback, progress_stage,
                                min(progress_end, percent))
            if progress_stage:
                _notify(progress_callback, progress_stage, progress_end)
    except (SubtitleCancelled, SubtitleError):
        raise
    except (OSError, RuntimeError, zipfile.BadZipFile) as exc:
        raise SubtitleError(
            'Subtitle component archive could not be extracted') from exc


def _prepare_runtime(progress_callback: Optional[ProgressCallback],
                     cancel_check: Optional[CancelCheck]) -> tuple[str, str, str]:
    with _interprocess_cache_lock(
            f'whisper-{WHISPER_VERSION}', cancel_check):
        return _prepare_runtime_locked(
            progress_callback, cancel_check)


def _prepare_runtime_locked(
        progress_callback: Optional[ProgressCallback],
        cancel_check: Optional[CancelCheck]) -> tuple[str, str, str]:
    with _runtime_lock:
        _check_cancel(cancel_check)
        root = _cache_root()
        archive = os.path.join(root, 'downloads', f'whisper-{WHISPER_VERSION}-x64.zip')
        runtime_dir = os.path.join(root, 'whisper', WHISPER_VERSION)
        exe = _verify_whisper_install(
            runtime_dir, cancel_check=cancel_check)
        if not exe:
            _notify(progress_callback, 'runtime', 0)
            _download_verified(
                WHISPER_ARCHIVE_URL, archive, WHISPER_ARCHIVE_SIZE,
                WHISPER_ARCHIVE_SHA256, 'runtime', progress_callback, cancel_check)
            parent = os.path.dirname(runtime_dir)
            os.makedirs(parent, exist_ok=True)
            temp_dir = tempfile.mkdtemp(prefix='whisper-install-', dir=parent)
            try:
                _safe_extract_zip(
                    archive, temp_dir, cancel_check=cancel_check)
                if not _verify_whisper_install(
                        temp_dir, require_marker=False,
                        cancel_check=cancel_check):
                    raise SubtitleError(
                        'whisper.cpp runtime failed integrity verification')
                with open(os.path.join(temp_dir, '.source-sha256'), 'w', encoding='ascii') as handle:
                    handle.write(WHISPER_ARCHIVE_SHA256)
                if os.path.isdir(runtime_dir):
                    shutil.rmtree(runtime_dir)
                os.replace(temp_dir, runtime_dir)
                temp_dir = ''
            finally:
                if temp_dir:
                    shutil.rmtree(temp_dir, ignore_errors=True)
            exe = _verify_whisper_install(
                runtime_dir, cancel_check=cancel_check)
        if not exe:
            raise SubtitleError('Unable to install whisper.cpp')

        model = os.path.join(root, 'models', MODEL_NAME)
        _notify(progress_callback, 'model', 0)
        _download_verified(
            MODEL_URL, model, MODEL_SIZE, MODEL_SHA256,
            'model', progress_callback, cancel_check)
        vad_model = os.path.join(root, 'models', VAD_MODEL_NAME)
        _download_verified(
            VAD_MODEL_URL, vad_model, VAD_MODEL_SIZE, VAD_MODEL_SHA256,
            'model', progress_callback, cancel_check)
        return exe, model, vad_model


def _run_process(args: list[str], log_path: str,
                 cancel_check: Optional[CancelCheck]) -> None:
    creationflags = getattr(subprocess, 'CREATE_NO_WINDOW', 0) if os.name == 'nt' else 0
    with open(log_path, 'wb') as log_handle:
        process = subprocess.Popen(
            args, stdin=subprocess.DEVNULL, stdout=log_handle,
            stderr=subprocess.STDOUT, creationflags=creationflags)
        while process.poll() is None:
            if cancel_check and cancel_check():
                process.terminate()
                try:
                    process.wait(timeout=3)
                except subprocess.TimeoutExpired:
                    process.kill()
                    process.wait(timeout=3)
                raise SubtitleCancelled('Subtitle generation cancelled')
            time.sleep(0.25)
        if process.returncode != 0:
            raise SubtitleError(f'Subtitle process exited with code {process.returncode}')


def _extract_audio(video_path: str, wav_path: str, log_path: str,
                   cancel_check: Optional[CancelCheck]) -> None:
    ffmpeg = locate_ffmpeg()
    if not ffmpeg:
        raise SubtitleError('FFmpeg is unavailable')
    _run_process([
        ffmpeg, '-nostdin', '-hide_banner', '-loglevel', 'error', '-y',
        '-i', video_path, '-vn', '-ac', '1', '-ar', '16000',
        '-c:a', 'pcm_s16le', wav_path,
    ], log_path, cancel_check)


def _run_whisper(exe: str, model: str, vad_model: str, wav_path: str,
                 output_base: str, log_path: str,
                 cancel_check: Optional[CancelCheck]) -> str:
    threads = max(1, min(8, (os.cpu_count() or 4) - 1))
    args = [
        exe, '-m', model, '-f', wav_path, '-l', 'ja',
        '-osrt', '-of', output_base, '-np', '-t', str(threads),
        '-bs', '1', '-bo', '1', '-nf', '-sns',
        '--vad', '-vm', vad_model,
    ]
    _run_process(args, log_path, cancel_check)
    result = output_base + '.srt'
    if not os.path.isfile(result):
        raise SubtitleError('Whisper did not create an SRT subtitle file')
    return result


def _atomic_copy(source: str, destination: str) -> None:
    destination_dir = os.path.dirname(destination)
    os.makedirs(destination_dir, exist_ok=True)
    descriptor, temp = tempfile.mkstemp(
        prefix=os.path.basename(destination) + '.',
        suffix='.tmp', dir=destination_dir)
    os.close(descriptor)
    try:
        shutil.copyfile(source, temp)
        os.replace(temp, destination)
        temp = ''
    finally:
        if temp:
            try:
                os.remove(temp)
            except FileNotFoundError:
                pass


def _safe_manifest_path(root: str, relative_path: str) -> str:
    relative = str(relative_path or '').replace('\\', '/')
    if not relative or relative.startswith('/') or ':' in relative:
        raise SubtitleError('Local translation model manifest has an unsafe path')
    target = os.path.abspath(os.path.join(root, *relative.split('/')))
    if os.path.commonpath([os.path.abspath(root), target]) != os.path.abspath(root):
        raise SubtitleError('Local translation model manifest has an unsafe path')
    return target


def _read_translation_manifest(
        root: str,
        cancel_check: Optional[CancelCheck] = None) -> dict:
    manifest_path = os.path.join(root, 'manifest.json')
    try:
        manifest_verified = (
            bool(TRANSLATION_MANIFEST_SHA256)
            and _sha256(manifest_path, cancel_check).lower()
            == TRANSLATION_MANIFEST_SHA256.lower())
    except OSError:
        manifest_verified = False
    if not manifest_verified:
        raise SubtitleError('Local translation model manifest failed verification')
    try:
        with open(manifest_path, 'r', encoding='utf-8') as handle:
            manifest = json.load(handle)
    except (OSError, ValueError, TypeError) as exc:
        raise SubtitleError('Local translation model manifest is invalid') from exc
    if str(manifest.get('pack_version')) != TRANSLATION_PACK_VERSION:
        raise SubtitleError('Local translation model pack version is invalid')
    files = manifest.get('files')
    models = manifest.get('models')
    if not isinstance(files, list) or not isinstance(models, dict):
        raise SubtitleError('Local translation model manifest is incomplete')
    for key in ('ja-en', 'en-zh'):
        model = models.get(key)
        if not isinstance(model, dict) or not model.get('path'):
            raise SubtitleError('Local translation model manifest is incomplete')
    return manifest


def _verify_translation_install(
        root: str, require_marker: bool = True,
        progress_callback: Optional[ProgressCallback] = None,
        cancel_check: Optional[CancelCheck] = None,
        progress_stage: Optional[str] = None,
        progress_start: int = 0,
        progress_end: int = 100) -> dict:
    _check_cancel(cancel_check)
    marker = os.path.join(root, '.source-sha256')
    if require_marker:
        try:
            with open(marker, 'r', encoding='ascii') as handle:
                if handle.read().strip().lower() != TRANSLATION_PACK_SHA256.lower():
                    raise SubtitleError('Local translation model marker is invalid')
        except OSError as exc:
            raise SubtitleError('Local translation model marker is missing') from exc

    manifest = _read_translation_manifest(root, cancel_check)
    entries = manifest['files']
    if progress_stage:
        _notify(progress_callback, progress_stage, progress_start)
    for index, entry in enumerate(entries):
        _check_cancel(cancel_check)
        if not isinstance(entry, dict):
            raise SubtitleError('Local translation model manifest is invalid')
        path = _safe_manifest_path(root, entry.get('path', ''))
        try:
            expected_size = int(entry['size'])
            expected_sha256 = str(entry['sha256'])
        except (KeyError, TypeError, ValueError) as exc:
            raise SubtitleError('Local translation model manifest is invalid') from exc
        if not _is_verified(
                path, expected_size, expected_sha256, cancel_check):
            raise SubtitleError('Local translation model failed integrity verification')
        if progress_stage and entries:
            percent = progress_start + int(
                (index + 1) * (progress_end - progress_start)
                / len(entries))
            _notify(
                progress_callback, progress_stage,
                min(progress_end, percent))

    resolved: dict[str, str] = {}
    for key in ('ja-en', 'en-zh'):
        _check_cancel(cancel_check)
        model_dir = _safe_manifest_path(root, manifest['models'][key]['path'])
        for filename in (
                'config.json', 'model.bin', 'shared_vocabulary.json',
                'source.spm', 'target.spm'):
            if not os.path.isfile(os.path.join(model_dir, filename)):
                raise SubtitleError('Local translation model is incomplete')
        if (
                key == 'ja-en'
                and not os.path.isfile(os.path.join(model_dir, 'vocab.json'))):
            raise SubtitleError(
                'Local Japanese translation tokenizer vocabulary is missing')
        resolved[key] = model_dir
    if progress_stage:
        _notify(progress_callback, progress_stage, progress_end)
    return resolved


def _cleanup_translation_install_dirs(parent: str) -> None:
    parent = os.path.abspath(parent)
    prefix = f'translation-v{TRANSLATION_PACK_VERSION}-install-'
    try:
        names = os.listdir(parent)
    except OSError:
        return
    for name in names:
        if not name.startswith(prefix):
            continue
        target = os.path.abspath(os.path.join(parent, name))
        if os.path.commonpath([parent, target]) != parent:
            continue
        if os.path.isdir(target):
            shutil.rmtree(target, ignore_errors=True)


def _remove_translation_cache_path(path: str, parent: str) -> None:
    path = os.path.abspath(path)
    parent = os.path.abspath(parent)
    if os.path.commonpath([parent, path]) != parent or path == parent:
        raise SubtitleError('Unsafe local translation cache path')
    if os.path.isdir(path):
        shutil.rmtree(path)
    elif os.path.exists(path):
        os.remove(path)


def _remove_translation_cache_path_best_effort(path: str, parent: str) -> None:
    try:
        _remove_translation_cache_path(path, parent)
    except (OSError, SubtitleError):
        # An obsolete backup must not block an already verified active runtime.
        pass


def _prepare_translation_runtime(
        progress_callback: Optional[ProgressCallback],
        cancel_check: Optional[CancelCheck]) -> dict[str, str]:
    lock_name = f'translation-v{TRANSLATION_PACK_VERSION}'
    with _interprocess_cache_lock(lock_name, cancel_check):
        return _prepare_translation_runtime_locked(
            progress_callback, cancel_check)


def _prepare_translation_runtime_locked(
        progress_callback: Optional[ProgressCallback],
        cancel_check: Optional[CancelCheck]) -> dict[str, str]:
    with _translation_runtime_lock:
        _check_cancel(cancel_check)
        root = _cache_root()
        runtime_dir = os.path.join(
            root, 'translation', f'v{TRANSLATION_PACK_VERSION}')
        parent = os.path.dirname(runtime_dir)
        os.makedirs(parent, exist_ok=True)
        _cleanup_translation_install_dirs(parent)
        previous = runtime_dir + '.previous'
        if not os.path.exists(runtime_dir) and os.path.exists(previous):
            os.replace(previous, runtime_dir)
        try:
            installed = _verify_translation_install(
                runtime_dir, cancel_check=cancel_check)
            if os.path.exists(previous):
                _remove_translation_cache_path_best_effort(previous, parent)
            return installed
        except SubtitleCancelled:
            raise
        except SubtitleError:
            pass

        # A process may have terminated in the tiny interval between moving
        # the previous runtime aside and activating the new one.  Prefer a
        # fully verified backup over downloading again.
        if os.path.exists(previous):
            try:
                _verify_translation_install(
                    previous, cancel_check=cancel_check)
            except SubtitleCancelled:
                raise
            except SubtitleError:
                pass
            else:
                _remove_translation_cache_path(runtime_dir, parent)
                os.replace(previous, runtime_dir)
                return _verify_translation_install(
                    runtime_dir, cancel_check=cancel_check)

        if not TRANSLATION_PACK_SIZE or not TRANSLATION_PACK_SHA256:
            raise SubtitleError('Local translation model pack is not configured')
        _notify(progress_callback, 'translation_model', 0)
        archive = os.path.join(root, 'downloads', TRANSLATION_PACK_NAME)

        def download_progress(
                _stage: str, percent: Optional[int]) -> None:
            mapped = (
                None if percent is None
                else min(70, max(0, int(percent * 0.70))))
            _notify(
                progress_callback, 'translation_model', mapped)

        _download_verified(
            TRANSLATION_PACK_URL, archive, TRANSLATION_PACK_SIZE,
            TRANSLATION_PACK_SHA256, 'translation_model',
            download_progress, cancel_check)

        temp_dir = tempfile.mkdtemp(
            prefix=f'translation-v{TRANSLATION_PACK_VERSION}-install-',
            dir=parent)
        try:
            _safe_extract_zip(
                archive, temp_dir, progress_callback, cancel_check,
                'translation_model', 70, 85)
            _verify_translation_install(
                temp_dir, require_marker=False,
                progress_callback=progress_callback,
                cancel_check=cancel_check,
                progress_stage='translation_model',
                progress_start=85,
                progress_end=95)
            _check_cancel(cancel_check)
            with open(
                    os.path.join(temp_dir, '.source-sha256'),
                    'w', encoding='ascii') as handle:
                handle.write(TRANSLATION_PACK_SHA256)
            if os.path.exists(previous):
                _remove_translation_cache_path_best_effort(previous, parent)
            had_previous = os.path.exists(runtime_dir)
            if had_previous:
                os.replace(runtime_dir, previous)
            try:
                os.replace(temp_dir, runtime_dir)
                temp_dir = ''
            except Exception:
                if had_previous and not os.path.exists(runtime_dir):
                    os.replace(previous, runtime_dir)
                raise
            if os.path.exists(previous):
                _remove_translation_cache_path(previous, parent)
        finally:
            if temp_dir:
                shutil.rmtree(temp_dir, ignore_errors=True)

        # The extracted, per-file verified pack is sufficient.  Do not keep a
        # second ~140 MB archive in the user's cache.
        try:
            os.remove(archive)
            _verified_paths.pop(os.path.abspath(archive), None)
        except OSError:
            pass
        installed = _verify_translation_install(
            runtime_dir,
            progress_callback=progress_callback,
            cancel_check=cancel_check,
            progress_stage='translation_model',
            progress_start=95,
            progress_end=100)
        _notify(progress_callback, 'translation_model', 100)
        return installed


def _translation_memory_path() -> str:
    return os.path.join(
        _cache_root(), 'translation', 'translation-memory.sqlite3')


def _translation_memory_version() -> str:
    from subtitle_domain import DOMAIN_VERSION
    return (
        f'{TRANSLATION_ENGINE_VERSION}+{DOMAIN_VERSION}'
        f'+manifest:{TRANSLATION_MANIFEST_SHA256}')


def _translation_api_endpoint(profile) -> str:
    """Return the canonical, non-secret endpoint used in cache identity."""
    provider = str(profile.provider)
    model = str(profile.model)
    base_url = str(profile.base_url).rstrip('/')
    if provider in ('openai', 'openai-compatible'):
        endpoint = (
            base_url if base_url.endswith('/chat/completions')
            else base_url + '/chat/completions'
        )
    elif provider == 'anthropic':
        endpoint = (
            base_url if base_url.endswith('/messages')
            else base_url + '/messages'
        )
    elif provider == 'gemini':
        endpoint = (
            base_url if base_url.endswith(':generateContent')
            else base_url + '/models/'
            + quote(model, safe='-._') + ':generateContent'
        )
    else:
        raise SubtitleError('Unsupported translation provider')
    parsed = urlsplit(endpoint)
    return urlunsplit((
        parsed.scheme.lower(),
        parsed.netloc.lower(),
        parsed.path,
        '',
        '',
    ))


def _translation_api_memory_version(profile) -> str:
    """Isolate API cache rows by provider, model, and endpoint—not API key."""
    from subtitle_domain import DOMAIN_VERSION
    identity = json.dumps(
        {
            'provider': str(profile.provider),
            'model': str(profile.model),
            'endpoint': _translation_api_endpoint(profile),
        },
        ensure_ascii=True,
        sort_keys=True,
        separators=(',', ':'),
    ).encode('utf-8')
    digest = hashlib.sha256(identity).hexdigest()
    return f'llm-subtitle-v1+{DOMAIN_VERSION}+profile:{digest}'


def _translation_memory_lookup(
        texts: list[str], source_language: str,
        target_language: str,
        engine_version: Optional[str] = None) -> dict[str, str]:
    if not texts:
        return {}
    version = engine_version or _translation_memory_version()
    path = _translation_memory_path()
    if not os.path.isfile(path):
        return {}
    try:
        with _translation_memory_lock, sqlite3.connect(path, timeout=5) as db:
            rows = []
            for start in range(0, len(texts), 500):
                batch = texts[start:start + 500]
                placeholders = ','.join('?' for _ in batch)
                query = (
                    'SELECT source_text, translated_text FROM translations '
                    'WHERE engine_version = ? AND source_language = ? '
                    f'AND target_language = ? '
                    f'AND source_text IN ({placeholders})'
                )
                rows.extend(db.execute(
                    query,
                    (version, source_language,
                     target_language, *batch),
                ).fetchall())
        return {str(source): str(translated) for source, translated in rows}
    except sqlite3.Error:
        # Translation must remain usable if an old or locked cache is damaged.
        return {}


def _translation_memory_store(
        pairs: dict[str, str], source_language: str,
        target_language: str,
        engine_version: Optional[str] = None) -> None:
    if not pairs:
        return
    version = engine_version or _translation_memory_version()
    path = _translation_memory_path()
    try:
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with _translation_memory_lock, sqlite3.connect(path, timeout=5) as db:
            db.execute('PRAGMA journal_mode=WAL')
            db.execute(
                'CREATE TABLE IF NOT EXISTS translations ('
                'engine_version TEXT NOT NULL, '
                'source_language TEXT NOT NULL, '
                'target_language TEXT NOT NULL, '
                'source_text TEXT NOT NULL, '
                'translated_text TEXT NOT NULL, '
                'updated_at INTEGER NOT NULL, '
                'PRIMARY KEY (engine_version, source_language, '
                'target_language, source_text))')
            now = int(time.time())
            db.executemany(
                'INSERT OR REPLACE INTO translations '
                '(engine_version, source_language, target_language, '
                'source_text, translated_text, updated_at) '
                'VALUES (?, ?, ?, ?, ?, ?)',
                [
                    (version, source_language,
                     target_language, source, translated, now)
                    for source, translated in pairs.items()
                ],
            )
    except (OSError, sqlite3.Error):
        # A cache write is an optimization and must never discard subtitles.
        return


def _validate_translation(
        source: str, translated: str,
        origin: str = 'Local translation model') -> str:
    cleaned = re.sub(r'\s+', ' ', str(translated or '')).strip()
    if source and not cleaned:
        raise SubtitleError(f'{origin} returned an empty cue')
    if '-->' in cleaned or re.search(
            r'\d{1,2}:\d{2}:\d{2}[,.]\d{3}', cleaned):
        raise SubtitleError(f'{origin} returned timing text')
    if len(cleaned) > max(240, len(source) * 12 + 80):
        raise SubtitleError(f'{origin} returned an invalid cue')
    return cleaned


def _clean_model_text(text: str) -> str:
    return re.sub(
        r'\s+', ' ',
        unicodedata.normalize('NFKC', str(text or ''))).strip()


def _restore_terminal_punctuation(
        source: str, translated: str, target_language: str) -> str:
    result = str(translated or '').strip()
    if not source or not result:
        return result
    if target_language == 'zh-TW':
        result = re.sub(r'\?$', '？', result)
        result = re.sub(r'!$', '！', result)
        result = re.sub(r'\.$', '。', result)
    if re.search(r'[.!?。！？…]$', result):
        return result
    source = source.rstrip()
    if source.endswith(('?', '？')):
        return result + ('？' if target_language == 'zh-TW' else '?')
    if source.endswith(('!', '！')):
        return result + ('！' if target_language == 'zh-TW' else '!')
    if source.endswith(('...', '…')):
        return result + ('……' if target_language == 'zh-TW' else '…')
    if source.endswith(('.', '。')):
        return result + ('。' if target_language == 'zh-TW' else '.')
    return result


def _run_local_model(
        model_dir: str, texts: list[str],
        target_token: Optional[str],
        cancel_check: Optional[CancelCheck]) -> list[str]:
    _check_cancel(cancel_check)
    try:
        import ctranslate2
        import sentencepiece as sentencepiece
    except Exception as exc:
        raise SubtitleError(
            'Local translation runtime is unavailable; reinstall the app') from exc

    _check_cancel(cancel_check)
    source_processor = sentencepiece.SentencePieceProcessor(
        model_file=os.path.join(model_dir, 'source.spm'))
    target_processor = sentencepiece.SentencePieceProcessor(
        model_file=os.path.join(model_dir, 'target.spm'))
    source_vocabulary = None
    vocabulary_path = os.path.join(model_dir, 'vocab.json')
    if os.path.isfile(vocabulary_path):
        try:
            with open(vocabulary_path, 'r', encoding='utf-8') as handle:
                vocabulary_payload = json.load(handle)
            if (
                    not isinstance(vocabulary_payload, dict)
                    or '<unk>' not in vocabulary_payload):
                raise ValueError('invalid tokenizer vocabulary')
            source_vocabulary = frozenset(
                str(token) for token in vocabulary_payload)
        except (OSError, TypeError, ValueError) as exc:
            raise SubtitleError(
                'Local translation tokenizer vocabulary is invalid') from exc
    threads = max(1, min(8, (os.cpu_count() or 4) - 1))
    try:
        _check_cancel(cancel_check)
        translator = ctranslate2.Translator(
            model_dir, device='cpu', compute_type='int8',
            inter_threads=1, intra_threads=threads)
        _check_cancel(cancel_check)
        translated: list[str] = []
        # Smaller independent batches keep cancellation responsive without
        # materially reducing CPU throughput for subtitle-sized cues.
        batch_size = 16
        for start in range(0, len(texts), batch_size):
            _check_cancel(cancel_check)
            batch = texts[start:start + batch_size]
            source_tokens = []
            for text in batch:
                tokens = source_processor.encode(text, out_type=str)
                if source_vocabulary is not None:
                    tokens = [
                        token if token in source_vocabulary else '<unk>'
                        for token in tokens
                    ]
                if target_token:
                    tokens.insert(0, target_token)
                # Models converted from Transformers do not add tokenizer
                # special tokens automatically.
                tokens.append('</s>')
                source_tokens.append(tokens)
            results = translator.translate_batch(
                source_tokens, beam_size=4, max_batch_size=batch_size,
                batch_type='examples', max_decoding_length=160)
            _check_cancel(cancel_check)
            if len(results) != len(batch):
                raise SubtitleError(
                    'Local translation model returned the wrong cue count')
            for result in results:
                tokens = [
                    token for token in result.hypotheses[0]
                    if token not in ('<s>', '</s>', '<pad>')
                    and not re.fullmatch(r'>>[^<>]+<<', token)
                ]
                translated.append(target_processor.decode(tokens).strip())
        return translated
    except SubtitleError:
        raise
    except Exception as exc:
        raise SubtitleError(
            f'Local translation failed: {type(exc).__name__}') from exc


@lru_cache(maxsize=1)
def _taiwan_converter():
    from opencc import OpenCC
    return OpenCC('s2twp')


def _to_taiwan_chinese(text: str) -> str:
    try:
        converted = _taiwan_converter().convert(text)
    except Exception as exc:
        raise SubtitleError(
            'Taiwan Chinese conversion runtime is unavailable') from exc
    from subtitle_domain import postprocess_taiwan
    return postprocess_taiwan(converted)


def _translate_direct(
        texts: list[str], source_language: str, target_language: str,
        progress_stage: str,
        progress_callback: Optional[ProgressCallback],
        cancel_check: Optional[CancelCheck],
        polish_english_output: bool = True) -> list[str]:
    from subtitle_domain import (
        exact_translation,
        normalize_cue,
        postprocess_english,
    )

    if (source_language, target_language) not in {
            ('ja', 'en'), ('en', 'zh-TW')}:
        raise SubtitleError(
            f'Unsupported local translation pair: '
            f'{source_language} -> {target_language}')
    if not texts:
        return []

    model_inputs = [_clean_model_text(text) for text in texts]
    normalized = [normalize_cue(text) for text in model_inputs]
    unique = list(dict.fromkeys(text for text in normalized if text))
    representative = {}
    for key, model_input in zip(normalized, model_inputs):
        if key and key not in representative:
            # Use the normalized key for model work so decorative terminal
            # punctuation does not make deduplication input-order dependent.
            representative[key] = key
    resolved: dict[str, str] = {}

    if source_language == 'ja':
        for source in unique:
            override = exact_translation(
                representative[source], source_language, target_language)
            if override is not None:
                resolved[source] = override

    misses = [source for source in unique if source not in resolved]
    cached = _translation_memory_lookup(
        misses, source_language, target_language)
    for source, translated in cached.items():
        try:
            resolved[source] = _validate_translation(source, translated)
        except SubtitleError:
            # Treat a malformed cache record as a miss so the local model can
            # replace it instead of poisoning this cue indefinitely.
            continue
    misses = [source for source in misses if source not in resolved]

    if misses:
        models = _prepare_translation_runtime(
            progress_callback, cancel_check)
        model_key = 'ja-en' if source_language == 'ja' else 'en-zh'
        target_token = (
            '>>cmn_Hant<<' if target_language == 'zh-TW' else None)
        model_outputs = _run_local_model(
            models[model_key],
            [representative[source] for source in misses],
            target_token, cancel_check)
        if len(model_outputs) != len(misses):
            raise SubtitleError(
                'Local translation model returned the wrong cue count')
        new_pairs: dict[str, str] = {}
        for source, translated in zip(misses, model_outputs):
            if target_language == 'zh-TW':
                translated = _to_taiwan_chinese(translated)
            translated = _restore_terminal_punctuation(
                representative[source], translated, target_language)
            translated = _validate_translation(source, translated)
            resolved[source] = translated
            new_pairs[source] = translated
        _translation_memory_store(
            new_pairs, source_language, target_language)

    output: list[str] = []
    for index, source in enumerate(normalized):
        _check_cancel(cancel_check)
        translated = '' if not source else resolved[source]
        if target_language == 'en' and polish_english_output:
            translated = postprocess_english(translated)
        translated = _restore_terminal_punctuation(
            model_inputs[index], translated, target_language)
        output.append(_validate_translation(source, translated))
        _notify(
            progress_callback, progress_stage,
            int((index + 1) * 100 / len(normalized)))
    return output


def _selected_translation_profile():
    """Load the selected provider without importing settings at app startup."""
    try:
        from translation_settings import get_translation_settings
        return get_translation_settings()
    except Exception as exc:
        raise SubtitleError(
            'Translation provider settings could not be loaded') from exc


@contextmanager
def _translation_profile_scope(profile):
    """Pin one provider choice for the duration of a subtitle job."""
    had_previous = hasattr(_translation_provider_state, 'profile')
    previous = getattr(_translation_provider_state, 'profile', None)
    _translation_provider_state.profile = profile
    try:
        yield
    finally:
        if had_previous:
            _translation_provider_state.profile = previous
        else:
            try:
                del _translation_provider_state.profile
            except AttributeError:
                pass


def _translate_api_direct(
        texts: list[str], source_language: str, target_language: str,
        progress_stage: str,
        progress_callback: Optional[ProgressCallback],
        cancel_check: Optional[CancelCheck],
        profile) -> list[str]:
    """Translate Japanese cues directly with an explicitly selected provider."""
    from llm_translation import (
        LlmTranslationCancelled,
        LlmTranslationError,
        LlmTranslationSettings,
        translate_cues as translate_llm_cues,
    )
    from subtitle_domain import (
        exact_translation,
        normalize_cue,
        postprocess_english,
    )

    if source_language != 'ja' or target_language not in ('en', 'zh-TW'):
        raise SubtitleError(
            'External translation requires Japanese source subtitles')
    if not texts:
        return []

    model_inputs = [_clean_model_text(text) for text in texts]
    normalized = [normalize_cue(text) for text in model_inputs]
    unique = list(dict.fromkeys(text for text in normalized if text))
    representative = {
        key: key for key in normalized if key
    }
    resolved: dict[str, str] = {}
    for source in unique:
        override = exact_translation(
            representative[source], 'ja', target_language)
        if override is not None:
            resolved[source] = override

    cache_version = _translation_api_memory_version(profile)
    misses = [source for source in unique if source not in resolved]
    cached = _translation_memory_lookup(
        misses, 'ja', target_language, cache_version)
    for source, translated in cached.items():
        try:
            resolved[source] = _validate_translation(
                source, translated, 'Translation cache')
        except SubtitleError:
            continue
    misses = [source for source in misses if source not in resolved]

    if misses:
        llm_settings = LlmTranslationSettings(
            enabled=True,
            provider=str(profile.provider),
            model=str(profile.model),
            base_url=str(profile.base_url),
        )

        def report_api_progress(completed: int, total: int) -> None:
            percent = 0 if total <= 0 else int(completed * 80 / total)
            _notify(progress_callback, progress_stage, percent)

        try:
            result = translate_llm_cues(
                [representative[source] for source in misses],
                llm_settings,
                api_key=str(profile.api_key or ''),
                source_language='Japanese',
                target_language=(
                    'English'
                    if target_language == 'en'
                    else 'Taiwan Traditional Chinese'
                ),
                cancel_check=cancel_check,
                progress_callback=report_api_progress,
            )
        except LlmTranslationCancelled as exc:
            raise SubtitleCancelled(
                'Subtitle translation was cancelled') from exc
        except LlmTranslationError as exc:
            message = str(exc).strip()
            secret = str(profile.api_key or '')
            if secret:
                message = message.replace(secret, '[redacted]')
            if not message or len(message) > 300:
                message = (
                    f'{profile.provider} subtitle translation failed')
            # Do not retain a provider exception as ``__cause__``: defensive
            # callers may format chained tracebacks into crash logs, and a
            # third-party adapter must not get a chance to echo credentials.
            raise SubtitleError(message) from None
        except SubtitleCancelled:
            raise
        except Exception as exc:
            raise SubtitleError(
                f'{profile.provider} subtitle translation failed') from exc

        model_outputs = list(result.translations)
        if len(model_outputs) != len(misses):
            raise SubtitleError(
                f'{profile.provider} returned the wrong cue count')
        new_pairs: dict[str, str] = {}
        for source, translated in zip(misses, model_outputs):
            _check_cancel(cancel_check)
            if target_language == 'zh-TW':
                translated = _to_taiwan_chinese(translated)
            translated = _restore_terminal_punctuation(
                representative[source], translated, target_language)
            translated = _validate_translation(
                source, translated, f'{profile.provider} translation')
            resolved[source] = translated
            new_pairs[source] = translated
        _translation_memory_store(
            new_pairs, 'ja', target_language, cache_version)

    output: list[str] = []
    progress_start = 80 if misses else 0
    progress_span = 100 - progress_start
    for index, source in enumerate(normalized):
        _check_cancel(cancel_check)
        translated = '' if not source else resolved[source]
        if target_language == 'en':
            translated = postprocess_english(translated)
        translated = _restore_terminal_punctuation(
            model_inputs[index], translated, target_language)
        output.append(_validate_translation(
            source, translated, f'{profile.provider} translation'))
        _notify(
            progress_callback,
            progress_stage,
            progress_start
            + int((index + 1) * progress_span / len(normalized)),
        )
    return output


def translate_cues(
        texts: list[str], source_language: str, target_language: str,
        progress_stage: str,
        progress_callback: Optional[ProgressCallback] = None,
        cancel_check: Optional[CancelCheck] = None) -> list[str]:
    """Translate independent subtitle cues without changing cue boundaries."""
    _check_cancel(cancel_check)
    source_language = str(source_language)
    target_language = str(target_language)
    profile = getattr(_translation_provider_state, 'profile', None)
    if profile is not None and bool(getattr(profile, 'uses_api', False)):
        return _translate_api_direct(
            texts, source_language, target_language, progress_stage,
            progress_callback, cancel_check, profile)
    if (source_language, target_language) in {
            ('ja', 'en'), ('en', 'zh-TW')}:
        return _translate_direct(
            texts, source_language, target_language, progress_stage,
            progress_callback, cancel_check)
    if (source_language, target_language) == ('ja', 'zh-TW'):
        from subtitle_domain import exact_translation, normalize_cue
        model_inputs = [_clean_model_text(text) for text in texts]
        normalized = [normalize_cue(text) for text in model_inputs]
        output: list[Optional[str]] = [None] * len(texts)
        unresolved_indices: list[int] = []
        for index, (source, model_input) in enumerate(
                zip(normalized, model_inputs)):
            _check_cancel(cancel_check)
            if not source:
                output[index] = ''
                continue
            override = exact_translation(model_input, 'ja', 'zh-TW')
            if override is None:
                unresolved_indices.append(index)
            else:
                output[index] = _validate_translation(source, override)
        if unresolved_indices:
            japanese = [model_inputs[index] for index in unresolved_indices]

            def pivot_progress(offset: int):
                def report(stage: str, percent: Optional[int]) -> None:
                    if stage == 'translation_model':
                        _notify(progress_callback, stage, percent)
                    elif stage == progress_stage:
                        mapped = (
                            None if percent is None
                            else min(100, offset + int(percent / 2)))
                        _notify(progress_callback, progress_stage, mapped)
                return report

            english = _translate_direct(
                japanese, 'ja', 'en', progress_stage,
                pivot_progress(0), cancel_check,
                polish_english_output=False)
            chinese = _translate_direct(
                english, 'en', 'zh-TW', progress_stage,
                pivot_progress(50), cancel_check)
            for index, translated in zip(unresolved_indices, chinese):
                _check_cancel(cancel_check)
                output[index] = translated
        _check_cancel(cancel_check)
        final = [str(item or '') for item in output]
        _notify(progress_callback, progress_stage, 100)
        _check_cancel(cancel_check)
        return final
    raise SubtitleError(
        f'Unsupported local translation pair: '
        f'{source_language} -> {target_language}')


def translate_srt(
        source_path: str, destination_path: str, target_language: str,
        progress_stage: str,
        progress_callback: Optional[ProgressCallback] = None,
        cancel_check: Optional[CancelCheck] = None,
        source_language: str = 'ja') -> str:
    _check_cancel(cancel_check)
    with open(source_path, 'r', encoding='utf-8-sig') as handle:
        cues = parse_srt(handle.read())
    if not cues:
        _check_cancel(cancel_check)
        _atomic_write_text(destination_path, '')
        return destination_path

    translated_texts = translate_cues(
        [cue.text for cue in cues], source_language, target_language,
        progress_stage, progress_callback, cancel_check)
    if len(translated_texts) != len(cues):
        raise SubtitleError(
            'Local translation model returned the wrong cue count')
    translated_cues = [
        SrtCue(cue.index, cue.timing, translated_texts[index])
        for index, cue in enumerate(cues)
    ]
    _atomic_write_text(destination_path, render_srt(translated_cues))
    return destination_path


def translate_srt_to_zh_tw(
        source_path: str, destination_path: str,
        progress_callback: Optional[ProgressCallback] = None,
        cancel_check: Optional[CancelCheck] = None,
        source_language: str = 'ja') -> str:
    return translate_srt(
        source_path, destination_path, 'zh-TW', 'translate_zh',
        progress_callback, cancel_check, source_language=source_language)


def run_local_translation_diagnostic(destination_path: str) -> dict:
    """Run the packaged FuguMT -> OPUS-MT -> OpenCC path and save evidence.

    Both GUI entry points expose this only when an explicit diagnostic
    environment variable is present.  It gives release verification a way to
    exercise the actual frozen native runtime without opening a window or
    adding a normal user-facing command-line mode.
    """

    if not str(destination_path or '').strip():
        raise SubtitleError(
            'Local translation diagnostic output path is required')
    destination = os.path.abspath(
        os.path.expanduser(str(destination_path).strip()))

    source = '今日は撮影の前に機材を確認してから始めます。'
    english = translate_cues(
        [source], 'ja', 'en', 'diagnostic_translate_en')[0]
    taiwan = translate_cues(
        [source], 'ja', 'zh-TW', 'diagnostic_translate_zh')[0]
    from subtitle_domain import (
        DOMAIN_VERSION,
        GLOSSARY_VERSION,
        NONLEXICAL_COUNT,
        PHRASE_COUNT,
    )
    payload = {
        'schema': 1,
        'frozen': bool(getattr(sys, 'frozen', False)),
        'engine_version': _translation_memory_version(),
        'domain_version': DOMAIN_VERSION,
        'glossary_version': GLOSSARY_VERSION,
        'phrase_count': PHRASE_COUNT,
        'nonlexical_count': NONLEXICAL_COUNT,
        'source': source,
        'english': english,
        'taiwan': taiwan,
        'opencc': _to_taiwan_chinese('软件和视频在这里。'),
    }
    _atomic_write_text(
        destination,
        json.dumps(payload, ensure_ascii=False, sort_keys=True) + '\n')
    return payload


def run_llm_translation_diagnostic(destination_path: str) -> dict:
    """Exercise the selected external provider and save redacted evidence.

    The frozen entry points expose this only through the explicit
    ``JABLE_LLM_TRANSLATION_DIAGNOSTIC_OUTPUT`` release-diagnostic hook.  A
    unique, harmless cue prevents the request from being satisfied by the
    reviewed phrase corpus or translation memory.  Neither endpoint contents,
    credentials, source/response text, nor the full selected profile are
    written to disk.
    """

    if not str(destination_path or '').strip():
        raise SubtitleError(
            'LLM translation diagnostic output path is required')
    destination = os.path.abspath(
        os.path.expanduser(str(destination_path).strip()))

    profile = _selected_translation_profile()
    provider = str(getattr(profile, 'provider', '') or '').strip()
    model = str(getattr(profile, 'model', '') or '').strip()
    if not bool(getattr(profile, 'uses_api', False)):
        raise SubtitleError(
            'Select an external translation provider before this diagnostic')

    try:
        endpoint = _translation_api_endpoint(profile)
        endpoint_sha256 = hashlib.sha256(
            endpoint.encode('utf-8')).hexdigest()
        nonce = secrets.token_hex(8)
        source = (
            'これは字幕翻訳APIの接続診断です。'
            f'確認番号は{nonce}です。')
        with _translation_profile_scope(profile):
            translated = translate_cues(
                [source], 'ja', 'en', 'diagnostic_llm_translate_en')[0]
    except Exception:
        # Provider adapters intentionally expose only safe messages, but this
        # diagnostic is release plumbing: discard every chained detail so a
        # future adapter cannot leak a key, endpoint, or response body.
        label = provider if provider else 'External provider'
        raise SubtitleError(
            f'{label} LLM translation diagnostic failed') from None

    translated_bytes = translated.encode('utf-8')
    source_bytes = source.encode('utf-8')
    payload = {
        'schema': 1,
        'kind': 'llm_translation',
        'frozen': bool(getattr(sys, 'frozen', False)),
        'provider': provider,
        'model': model,
        'target_language': 'en',
        'cue_count': 1,
        'endpoint_sha256': endpoint_sha256,
        'source_characters': len(source),
        'source_sha256': hashlib.sha256(source_bytes).hexdigest(),
        'translation_characters': len(translated),
        'translation_sha256': hashlib.sha256(
            translated_bytes).hexdigest(),
    }
    _atomic_write_text(
        destination,
        json.dumps(payload, ensure_ascii=False, sort_keys=True) + '\n')
    return payload


def _atomic_write_text(destination: str, text: str) -> None:
    destination_dir = os.path.dirname(destination)
    os.makedirs(destination_dir, exist_ok=True)
    descriptor, temp = tempfile.mkstemp(
        prefix=os.path.basename(destination) + '.',
        suffix='.tmp', dir=destination_dir)
    try:
        handle = os.fdopen(
            descriptor, 'w', encoding='utf-8', newline='\n')
        descriptor = -1
        with handle:
            handle.write(text)
            handle.flush()
            os.fsync(handle.fileno())
        os.replace(temp, destination)
        temp = ''
    finally:
        if descriptor >= 0:
            os.close(descriptor)
        if temp:
            try:
                os.remove(temp)
            except FileNotFoundError:
                pass


def _existing(path: str) -> bool:
    try:
        if not os.path.isfile(path) or os.path.getsize(path) <= 0:
            return False
        with open(path, 'r', encoding='utf-8-sig') as handle:
            return bool(parse_srt(handle.read()))
    except (OSError, UnicodeError, SubtitleError):
        return False


def generate_subtitles(video_path: str, mode,
                       progress_callback: Optional[ProgressCallback] = None,
                       cancel_check: Optional[CancelCheck] = None) -> SubtitleResult:
    """Generate requested sidecar SRT files next to ``video_path``.

    Output names are ``.ja.srt``, ``.en.srt``, and ``.zh-TW.srt`` so media
    players can expose them as independently selectable subtitle tracks.
    """
    normalized = normalize_subtitle_mode(mode)
    requested = subtitle_languages(normalized)
    if not requested:
        return SubtitleResult((), ())
    video_path = os.path.abspath(video_path)
    if not os.path.isfile(video_path):
        raise SubtitleError('Downloaded video file was not found')

    paths = subtitle_paths(video_path)
    generated: list[str] = []
    with _generation_lock:
        _check_cancel(cancel_check)
        missing = [language for language in requested if not _existing(paths[language])]
        if not missing:
            return SubtitleResult(tuple(paths[language] for language in requested), ())

        _notify(progress_callback, 'queued', None)
        existing_japanese = paths['ja'] if _existing(paths['ja']) else None
        existing_english = paths['en'] if _existing(paths['en']) else None
        translation_profile = (
            _selected_translation_profile()
            if 'en' in missing or 'zh-TW' in missing
            else None
        )
        uses_api = bool(
            translation_profile is not None
            and getattr(translation_profile, 'uses_api', False)
        )
        need_japanese_source = bool(
            'ja' in missing
            or 'en' in missing
            or (
                'zh-TW' in missing
                and (uses_api or not existing_english)
            )
        )
        need_whisper = bool(need_japanese_source and not existing_japanese)
        exe = model = vad_model = None
        if need_whisper:
            exe, model, vad_model = _prepare_runtime(
                progress_callback, cancel_check)
        with tempfile.TemporaryDirectory(prefix='jable-subtitle-') as temp_dir:
            wav = os.path.join(temp_dir, 'audio.wav')
            log = os.path.join(temp_dir, 'process.log')
            if need_whisper:
                _notify(progress_callback, 'audio', None)
                _extract_audio(video_path, wav, log, cancel_check)

            japanese_source = existing_japanese
            need_japanese_pass = need_japanese_source
            if need_japanese_pass and not japanese_source:
                _notify(progress_callback, 'transcribe_ja', None)
                japanese_source = _run_whisper(
                    exe, model, vad_model, wav,
                    os.path.join(temp_dir, 'japanese'), log, cancel_check)

            if 'ja' in missing and japanese_source:
                _atomic_copy(japanese_source, paths['ja'])
                japanese_source = paths['ja']
                generated.append(paths['ja'])

            with _translation_profile_scope(translation_profile):
                if 'en' in missing:
                    if not japanese_source:
                        raise SubtitleError(
                            'Japanese transcription is unavailable')
                    _notify(progress_callback, 'translate_en', None)
                    try:
                        translate_srt(
                            japanese_source, paths['en'], 'en', 'translate_en',
                            progress_callback, cancel_check)
                        generated.append(paths['en'])
                    except SubtitleCancelled:
                        raise
                    except Exception:
                        if not _existing(paths['ja']):
                            _atomic_copy(japanese_source, paths['ja'])
                        raise

                if 'zh-TW' in missing:
                    english_source = (
                        paths['en']
                        if _existing(paths['en'])
                        else existing_english
                    )
                    if uses_api:
                        # External providers translate Japanese directly to
                        # the requested target.  They never pivot through an
                        # English sidecar or initialize the local model pack.
                        chinese_source = japanese_source
                        chinese_source_language = 'ja'
                    else:
                        # The local path prefers Japanese so reviewed exact
                        # phrases win, then pivots unknown cues through English.
                        chinese_source = japanese_source or english_source
                        chinese_source_language = (
                            'ja' if japanese_source else 'en')
                    if not chinese_source:
                        raise SubtitleError(
                            'Japanese or English transcription is unavailable')
                    try:
                        translate_srt_to_zh_tw(
                            chinese_source, paths['zh-TW'],
                            progress_callback, cancel_check,
                            source_language=chinese_source_language)
                        generated.append(paths['zh-TW'])
                    except SubtitleCancelled:
                        raise
                    except Exception:
                        # Preserve a useful timestamped fallback if setup or
                        # inference fails after a fresh transcription.
                        if japanese_source and not _existing(paths['ja']):
                            _atomic_copy(japanese_source, paths['ja'])
                        raise

        _notify(progress_callback, 'done', 100)
        return SubtitleResult(
            tuple(paths[language] for language in requested if _existing(paths[language])),
            tuple(generated),
        )
